### ISSUE TITLE
Saving deletes stops on lines that also have warps

### ISSUE THREAD

**Issue by MostlyHarmless85** [stepmania/stepmania#1091]
Whenever I save after I put a warp and a stop together on the same line, it deletes my stop and keeps the warp. I'm on the latest SM 5 version, so I'm pretty surprised that this is actually an issue.

**Comment by shakesoda** [comment]
the warp warps to a later beat as soon as the row crosses, so the stop goes, which seems to make sense.

what do you expect to happen instead? warp executing when the stop finishes?

**Comment by wolfman2000** [comment]
There is code that allows for stops and delays within a warp to be treated as a hittable, pause-able row. Perhaps that's the same logic @MostlyHarmless85 is after? You can hit the arrows on that row, have the stop go through its time, and then warp?

Please confirm my hypothesis.

**Comment by kyzentun** [comment]
H000 is an example of a simfile that does this.  I got it from waiei when he reported a different way that timing data was broken.  I tried editing and playing it, and I didn't see any stops disappear.  So there must be some detail for reproducing the bug that was left out of the issue.

**Comment by MostlyHarmless85** [comment]
My apologies for being so slow to respond. I really don't know how to explain this any better, so I'll try to use one of my simfile examples. Let's say I have a file that's 135 BPM and on each line I have a warp set to 1 and 0.225 stop together on the same line. When I hit play, everything works just as I intended perfectly. The problem happens when I hit save, and once the file is saved, the SM editor removes all the stops I had coupled with those warps. Try to put a stop and a warp on the same line and hit save to see what happens. I would be amazed if I'm the only person who has this problem. I even tried this out on a different PC and I still can't save a file with warps and stops together.

**Comment by Kingdaro** [comment]
For the record, I _think_ having a single warp at the start that lasts for the length of the stops, then putting stops in the middle of the warp will have the same effect.

**Comment by kyzentun** [comment]
With those instructions, I can reproduce it and start tracking down how it happens.

**Comment by kyzentun** [comment]
I found the culprit.  NotesWriterSM tries to turn the warps into negative stops when saving to the .sm file.  https://github.com/stepmania/stepmania/blob/master/src/NotesWriterSM.cpp#L102

Because there is already a stop on that row, it removes the existing stop.  The stop that is added is considered not notable because of this code in TimingSegments.h:
```bool IsNotable() const { return m_fSeconds > 0; }```
So the negative stop that is added to convert the warp is not saved.

I'm leaning towards a two step solution:  First, NotesWriter *must not* modify the data being saved.  

Second, detect stops and warps on the same row and don't save an sm file if it occurs.  It doesn't seem worth the effort to try to change the warp converting code to make this work.  If the warp converting code changes to use negative bpms instead of negative stops, then it needs to have special cases to handle bpm changes occurring in the affected area.  The current code should actually have a special case for handling stops that occur in the area of the warp.  But that probably wouldn't actually give something that always plays the same way.

So I guess .sm files of simfiles that use warps are just inherently broken because the .sm format doesn't have warps and negative stops/bpms can't do the same things.

**Comment by kyzentun** [comment]
After a bit of thinking, I decided to handle stops/warps/delays that occur on the same row by summing the values.  At 135 bpm a beat is 444ms.  So the warp gets converted to a -444ms stop.  Then the 225ms stop is added, and the result is a -219ms stop.

This fixes the problem of stops disappearing when there is a warp on the same row, and seems like a reasonable compromise for the .sm format.

I'll backport this commit to the master or 5_0 branch if someone else ever decides to make another 5.0.x release.

https://github.com/stepmania/stepmania/commit/4647d6abcb244c9531368cb69c8afeb46dc24c92

**Comment by kyzentun** [comment]
Backported to master.  https://github.com/stepmania/stepmania/commit/a0d6658a6576dba88d4a2545448ecfe181876d56
