### ISSUE TITLE
[5.1-git] Speed mod issues across players without profiles.

### ISSUE THREAD

**Issue by MrThatKid** [stepmania/stepmania#1117]
I'll use TaroNuke's Decieve your Insight file, which does mods, but no speed change mods (should work with any speed). The file itself is shown here: [https://www.youtube.com/watch?v=prp1l6nQh1w](https://www.youtube.com/watch?v=prp1l6nQh1w)
In 5.1, start a versus game with no local profiles. Change player 1's mod to something else, say 2.5x
Once the actual mods (not screen shifting related) start, Player 1's speed changes instantly back to m250 (the default.) at ~41 seconds into the file (~48 seconds for the video)
Or: Change Player 2 to something different instead. Both players will have the speed that p2 set, and BOTH get their speed reverted at that part.
This seems to only happen under the default theme and not other themes like Simply Love-SM5
Version: StepMania5.1-git-b5b1e30
Compiled 20160517 @ 04:56:39 (build b5b1e30), Ubuntu 16.04 64-bit.

**Comment by kyzentun** [comment]
Short answer:  The compatibility mode (aka, defective mode) for supporting old gimmicks assumes that gimmick simfiles will force the player to use a specific speed mod.

It happens because things that touch the old mod system (like that gimmick file, or themes that haven't been updated) switch the newfield into defective mode.  That disables the new modifier system, and makes it use only the old system.  The new code to apply speed mods only applies them to the new mod system.

**Comment by MrThatKid** [comment]
I found that using a (local) profile with a newfield_prefs configured makes this problem not appear to happen as the speed is the same as what the player wanted. I'm not sure when this file gets written/updated with new settings (such as note speed settings) in the default theme, but defective mode seems to use it for note speed.
Also, it still doesn't explain why changing P2's note speed settings changes P1's as well when no profiles are used.(it also happens in reverse: changing P1's speed settings changes P2's as well) That doesn't happen when profiles are either being used with both players shareing one (this has its' own problems that I'll say in a seperate bug report) or with each player using their own profile. This change on both sides happens with normal, non-gimmicky files too.

**Comment by kyzentun** [comment]
Defective mode kicks on in the middle of Deceive Your Insight because that's when it does something that turns on defective mode.  It doesn't show up in Simply Love because Simply Love is still using the old mod system, so it's already in defective mode.

Players using the same profile wasn't something I considered when creating the config system, so I'll have to investigate how they end up using the same config data and figure out a good solution.

**Comment by MrThatKid** [comment]
Ok, I understand that the older gimmick/mod files activate defective mode, and that makes the speed revert to the 'default' (this also shifts up the playfield a bit. No clue how to push it back down in defective mode with config files or other methods).
I can see why this happens with no profiles (probably no place to save the new speed settings) and why this doesn't happen with old themes.

With profiles used, I don't know when the new speed settings are supposed to be written to newfield_prefs (which defective mode seems to use for the 'default' speed in a profile, which is how I see it at least).

What I don't understand is the fact that I can override player 2's speed settings with my own (and vice versa) when profiles **aren't used at all**. This specific override of the other player's speed settings happens regardless of what file I play, and it's kind of odd. If that part wasn't clear at the start (it probably wasn't clear at all), then I apologize for that.

**Comment by kyzentun** [comment]
It is probably not reverting to the default speed when defective mode activates.  It's reverting to the speed in the PlayerOptions structure, which is either loaded from your profile or set by Preferences.ini.  If you're not looking closely, it can be easy to mistake m250 for 1x.

The playfield shifts a bit in defective mode because some modifiers depend on the y offset, the distance from the center of the field to the receptors.  If the y offset does not exactly match what the gimmick author expects, special effects like the "Driven Drop" don't work right.  At the moment, defective mode is using a couple metrics from the theme for calculating the y offset, but I'm considering hardcoding it to the ITG values for compatibility.

Players changing each other's speed mods when they aren't using separate profiles is a different bug, unrelated to the oddities that occur when defective mode is active.

**Comment by MrThatKid** [comment]
Ah, that makes sense. I guess I'll submit a new bug report for the 'players changing each other's speeds' problem, then. (This one can probably be closed if there's no need for it to be open now.)

**Comment by kyzentun** [comment]
I've been leaving this issue open because the question of how to handle speed mods when defective mode activates is a legitimate unsolved problem.  There's also the closely related problem of how to handle simfiles like "Border of Extacy" in the UFOS pack.  It doesn't actually do fancy mod effects, it just looks at the player modifiers to use Beat as a flag for turning on a couple special effects.  But because it touches the PlayerOptions structure, it turns on defective mode.

**Comment by kyzentun** [comment]
I decided to just apply the newfield_prefs speed mod to PlayerOptions, and if it doesn't work with the ITG y offset, it can be handled by per-song speed prefs.
