### ISSUE TITLE
[5.1-git] Players can change each other's speed mods when profiles aren't used.

### ISSUE THREAD

**Issue by MrThatKid** [stepmania/stepmania#1120]
In 5.1, start a versus game with no one using profiles. If you have any local profiles, temporaily rename the LocalProfiles directory to test this bug (You can always rename it back later).
Find any song chart that doesn't use mods (or defective mode might kick in. Makes it hard to test this bug), and go into player options.
Change player 1's speed mod to something noticably different. Don't change anything on Player 2's end. Start the song. Notice that both players have what Player 1 set for speed as opposed to both players having their own speed mods.
The same happens if you swap Player 1 and Player 2 in the instructions.
This doesn't happen once profiles get involved (Meaning, both players can have their own speed mods just fine).
Tested under default theme.
Version: StepMania5.1-git-0d9b024
Compiled 20160519 @ 01:04:55 (build 0d9b024) on Ubuntu 16.04 64-bit

**Comment by kyzentun** [comment]
https://github.com/stepmania/stepmania/commit/753e9aaef8686e4d873ce1bb70eced3ec8ce10f1

**Comment by kyzentun** [comment]
Side note:  I tried setting both players to use the same profile.  Player 1 got the config settings from the profile, player 2 got defaults.  I'm not sure why it came out this way.

**Comment by MrThatKid** [comment]
This commit did fix the problem, but it also does as you said: player 2 gets the defaults when both players use the same profile. I'm not sure why this happens either (especially since I know way less than you and the other developers).

**Comment by kyzentun** [comment]
I've figured out why only P1 gets the config.  https://github.com/stepmania/stepmania/blob/5_1_0/Themes/_fallback/Scripts/02%20lua_config_system.lua#L239

When a profile is loaded, the custom load function is not told what player it's being loaded for.  So the config system looks at the guid for the profile, then fetches the profile for each player to see who has a matching guid.  Since P1 has the matching guid, the config is loaded in the P1 slot both times.
