### ISSUE TITLE
(5.1) Save noteskin params to profile

### ISSUE THREAD

**Issue by 1033Forest** [stepmania/stepmania#1220]
This could be a useful feature: players could save the noteskin params on their profile. 

This way if they don't like the particles in the explosions, or want a different color scheme, they could keep it that way instead of having to go back and change it again and again.

**Comment by kyzentun** [comment]
The noteskin params *are* saved to the player's profile.

**Comment by kyzentun** [comment]
Search Logs/log.txt to see if this message is in there when it saves profiles:  "Could not open %s to save lua data."

**Comment by 1033Forest** [comment]
When I switch to that certain noteskin, it doesn't keep the params from the previous play. The current noteskin I have saved on my profile is a noteskin that doesn't use noteskin params.

**Comment by kyzentun** [comment]
I think there is something wrong with your Save folder that is preventing various config files from being written.  Or maybe some anti-virus is destroying the lua config files.

**Comment by latot** [comment]
Hi, i have the same problem, my configs like noteskins or similar don't are saved, thats one of the reasons i open this issue https://github.com/stepmania/stepmania/issues/1256
i use linux Gentoo 64, i check the logs.txt and i can't found any like ""Could not open"

**Comment by kyzentun** [comment]
The saving code expects a player number to be passed to the profile save function, but no player number was being passed.  Fixed in this commit: https://github.com/stepmania/stepmania/commit/f1dc5f3a08f6bd47e2e0c20d007c76d2a8c3b91e

If you're using current master, and it's still not saving, something else is wrong.

**Comment by latot** [comment]
Hi, are some requirements to this works, in say way, if i'm new in SM, i open the game, set some songs config and play, its saved that config? or i need do something else?

**Comment by kyzentun** [comment]
It's supposed to save when the rest of your profile saves.

**Comment by latot** [comment]
exist some condition to save the profile? like have a name? or theoretically always should be saved?

**Comment by latot** [comment]
Can you reopen this plis?
Actually my conf don't is saved.

**Comment by kyzentun** [comment]
This issue with conf not saving goes nowhere because I can never get any useful info out of anybody who reports the problem.

Does other lua config stuff like notefield prefs save?  Do theme options like putting the judgment under the field save?  
Does creating empty folders with the right names allow the game to save to the file?

notefield prefs should save to Save/LocalProfiles/00000000/notefield_prefs.lua
noteskin params should save to Save/LocalProfiles/00000000/notefield_prefs.lua
Per-player theme options like "Judgment Under Field" should save to Save/LocalProfiles/00000000/default_config/player_config.lua
Global theme options like "AutoSetStyle" should save to Save/default_config/theme_config.lua

**Comment by latot** [comment]
Hi, well playing i found this message, "J1 has no profile, player settings will not be saved.", that explain why the config don't is saved, but now, i make a profile and i lost all my scores, so i remove it and now are back.
About this behavior, i think its very mm, ugly. Lets think in a new ppl learning to play this game, it start, click play, select song play, etc, now don't are any part says its necessary make the profile, and while this ppl play never the configs will be saved, so the someone read the message, and make a profile, then it see lost the scores D:
personally don't make to much sense, so for this i have two questions:

Are some way to make a profile without lost the scores?
If a profile its absolutely necessary, its posible when we start playing ask to enter a name for the first profile?

Thx.

**Comment by kyzentun** [comment]
You could try manually copying the Stats.xml from the machine profile folder to the folder of your new profile.

Profiles are absolutely necessary, but discussion over when to automatically create them should go in a different issue.  Some people run stepmania in public or event places where creating profiles is not the right solution.

**Comment by latot** [comment]
mm, in this case maybe an option, to when we make the first profile ask if import the actual stats, or an options to import status between profiles (including the "no profile").
