### ISSUE TITLE
zenbuquan noteskin not loading correctly

### ISSUE THREAD

**Issue by AngledLuffa** [stepmania/stepmania#1281]
I tried StepMania 5.1 for the first time last night, and I was going through the noteskins to find one that pulsed with the beat the way the 5.0 default did.  When I tried zenbuquan, it didn't load correctly.  Attached is a screenshot of the error showing up in Edit mode, but the same error briefly flashed during actual gameplay, after which the arrows were not visible.

This is on Windows 10.  I had just upgraded from 5.0.10 to 5.1.-3

![error](https://cloud.githubusercontent.com/assets/3411033/18392272/0863e698-7666-11e6-964a-73c006887332.png)

**Comment by kyzentun** [comment]
https://github.com/stepmania/stepmania/commit/a6c1aa773ce26883c26c3ab351423498b3cf9222

**Comment by AngledLuffa** [comment]
Great, thanks!  I was having some difficulties getting it to build on Windows 10, so I had not tried from master.

By the way, is there a noteskin (should I say NoteSkin) that is closer to the look of the 5.0 default?  I found "delta" glows in time to the beat, but I liked the previous look a little more.

**Comment by kyzentun** [comment]
Katze is actually providing nightly builds for us once again.  http://smnightly.katzepower.com/job/Stepmania%20Nightly/94/

The default in 5.1.-3 is actually supposed to be similar to 5.0 default, but the colors were accidentally changed during editing, and I didn't realize until after release.  The white circles are left out because I didn't consider multi-actor taps when designing the system.

**Comment by AngledLuffa** [comment]
Thank you for both answers!  I look forward to trying them out.
