### ISSUE TITLE
oitg_zoom_mode_actor() doesn't work as intended.

### ISSUE THREAD

**Issue by MrThatKid** [stepmania/stepmania#1349]
In the 5_1-new branch and 5.0, The use of oitg_zoom_mode_actor() doesn't seem to affect how the playfields get zoomed at all when mods like Mini get used. This problem doesn't happen in the master branch.
I'll use the "Now is a Dull Party" SM5 conversion as an example. Can be gotten [here](https://www.mediafire.com/?eovnh6u143izos1)
Comparison between 5.0/5_1-new and master branch:
[5.0/5_1-new](http://imgur.com/a/PT5lc)
[master](http://imgur.com/a/TOLxe)
This was tested under StepMania5.1-git-5fcc473
Compiled 20161125 @ 17:38:36 (build 5fcc473) on Ubuntu 16.04

**Comment by kyzentun** [comment]
Replace this line with conditions for the m_oitg_zoom_mode flag like the other place that sets the zoom on the notefield.
https://github.com/stepmania/stepmania/blob/5_1-new/src/Player.cpp#L1634

Stepmania has been setting the notefield zoom in both Player::Update and Player::DrawPrimitives since 3.95:
https://github.com/sigatrev/Stepmania-3.95/blob/master/Player.cpp#L387
https://github.com/sigatrev/Stepmania-3.95/blob/master/Player.cpp#L694
