### ISSUE TITLE
Stepmania port to mobile or Unity3d?

### ISSUE THREAD

**Issue by coltcorrea** [stepmania/stepmania#1714]
Anyone interested in helping with a stepmania port to the mobile platform?  I have work for 2 years on new hardware for mobile and have a basic start of a dance game.  
[DigiBit Dance](https://www.youtube.com/watch?v=BwnzSxilE-0&t=3s)

Anyone interested in helping?   I can make my Unity code open source or help on a StepMania port to mobile if people are interested in this.  

My e-mail is: coltcorrea@myDigiBit.com

**Comment by cybik** [comment]
There's already *some* alpha Android code that doesn't require Unity integration.

**Comment by coltcorrea** [comment]
Unity provide iPhone and Android support.  This is why we used it.  For this game / project iPhone is equal to or even more important than Android in the USA at least.

**Comment by cybik** [comment]
Unity is a full engine. Stepmania's engine is RAGE, from what I recall.

If you really want to take a look, my code (however old) is at https://github.com/cybik/stepmania/tree/android_over_508 . I haven't had a chance to look at it recently, being on staff for another project.

@wolfman2000 any opinion on bringing in a complete external engine under Stepmania in order to run it on toasters?

**Comment by coltcorrea** [comment]
@cybik I have the start of a project working in Unity3D and it supports SM files already.  I am trying to see if anyone has an interest in joining the project or porting Stepmania.  Either one is good with me.  Just looking for advice from the experienced StepMania community.  Here is a video of DigiBit Dance on YouTube -> https://www.youtube.com/watch?v=BwnzSxilE-0&t=8s
