### ISSUE TITLE
StepMania-5.1.0-b2-mac.dmg cannot be mounted on El Capitan

### ISSUE THREAD

**Issue by jwalton** [stepmania/stepmania#1726]
Kind of a minor issue, but on my Mac Mini running El Capitan, I can't mount StepMania-5.1.0-b2-mac.dmg.  I get back "no mountable file systems".  The same thing mounts fine on my MBP running High Sierra.

**Comment by dguzek** [comment]
This is most likely caused by the dmg having been created as an APFS filesystem (Apple's new default for macOS 10.13) and El Capitan using HFS+.  Older versions of macOS do not have native support for mounting APFS volumes, and I've seen [other projects](https://github.com/timcharper/git_osx_installer/issues/100#issuecomment-350583005) have [similar issues](https://itch.io/post/487558) reported to them.

It is possible to package .dmg files using either APFS or HFS+, so I'll have to look into that for future releases.
