### ISSUE TITLE
Official, extensive documentation?

### ISSUE THREAD

**Issue by kangalioo** [stepmania/stepmania#1758]
Is there any official and somewhat extensive documentation for Stepmania? I know the wiki, but it's incomplete, to say the least. I can write some wiki pages using my own experience, but if there was official, extensive documentation, I would like to use that.

**Comment by kangalioo** [comment]
I didn't know of the Docs directory nor of your Lua guide. That's very helpful, thanks

When contributing to the wiki, I could probably write about the level editor... Also about the gameplay options (those that you can access right before starting a song). 
There is not so much specific I know much about. It's just that I've encountered lots of small features by accident that are also very useful and not documented (as far as I know): e.g. when pressing Tab the game seems to switch into "Turbo Mode".

**Comment by dguzek** [comment]
Hmm, so maybe like a *Beginner's Guide to StepMania*?  That does sound useful.  Would you be interested in writing up something like that?

Possible topics might include:
  * tips and tricks for general use that aren't apparent (like holding tab to speed up the UI, etc.)
  * how to author a stepchart  – I know [syncing guides](http://r21freak.com/phpbb3/viewtopic.php?f=38&t=12750) exist, but I don't know of any guides for *using* the built-in step editor
  * how to install SM5 – because it's [actually kind of tricky](https://github.com/dguzek/Simply-Love-SM5#troubleshooting-stepmania), [especially on macOS](https://github.com/dguzek/Simply-Love-SM5/wiki/Installing-StepMania-5.1-beta-on-macOS)

**Comment by kangalioo** [comment]
Yes, I'm interested. I'm not sure however if I can write a good-quality guide because I'm not that good of a writer... I will try and write some pages in the wiki soon :)

**Comment by dguzek** [comment]
Hi, @kangalioo.  I just wanted to check in.  Are you still interested in helping with this?

**Comment by kangalioo** [comment]
To be honest, not so much, sorry. Writing good wiki pages seemed a bit too daunting to me and also I switched to Etterna so I don't really use the original Stepmania anymore.

**Comment by dguzek** [comment]
Okay, I'll close this issue, then.
