### ISSUE TITLE
Enabled "Use dedicated buttons" and now my controls don't work

### ISSUE THREAD

**Issue by AURA547** [stepmania/stepmania#1764]
I was messing around with the options in SM5 via the SimplyLove theme and I enabled the option "Use dedicated buttons only" and now my controls don't so I can't go back and fix the problem, my friends said to fix it by going into the .ini files but tbh I'm not good at reading code or managing files in Stepmania all that much. If anyone can help me with my situation that would be great.

**Comment by coderjo** [comment]
What OS are you running on? That will partly determine where to find the file. (Or is there a portable.ini file next to the program?)

Basically, you need to open Save/Preferences.ini and find the line that says "OnlyDedicatedMenuButtons=1" and change it to a zero, then save the file and start SM5.

**Comment by xillmisa** [comment]
If you want to know about "dedicated buttons" feature, then this feature is for dance arcade machines having buttons and controls, that may input something different that keyboards don't, the "dedicated buttons" feature also has little security like public arcades, because public arcades has usb ports for saving data in flash sticks(in game "memory card"). When someone connects keyboard to public arcade's usb, then public arcade game won't recognise the keyboard unless owner enter service options and disable "dedicated buttons" feature.

**Comment by dguzek** [comment]
I'm going to close this issue now as it has been inactive for over four months.  @AURA547, if you still need assistance locating and editing your Preferences.ini file to reset your `OnlyDedicatedMenuButtons` setting, please respond to re-open this issue.
