### ISSUE TITLE
Instruction needed that on macos you must right-click on app to open first time

### ISSUE THREAD

**Issue by solsang** [stepmania/stepmania#1768]
There should be an instruction at the download section or FAQ, that to run Stepmania on macOS you need first time to right-click the stepmania.app and choose open, then you get the dialog where you can accept and open it for real. 

Also soon a warning has to be added that the current 32bit version of Stepmania will not work on macOS 2019 (10.15) - Mojave is the last macOS to support 32bit applications

**Comment by dguzek** [comment]
I've written these instruction for running SM5 for the first time on macOS: https://github.com/dguzek/Simply-Love-SM5/wiki/Installing-StepMania-5.1-beta-on-macOS

And, yes, it's true that SM5 no longer work on macOS 10.15.  I have spent some hours trying to get SM5.1-beta2 to build as a 64bit app to no avail.

**Comment by dguzek** [comment]
The guide for (currently) installing SM5 on macOS has been moved to StepMania's Wiki: https://github.com/stepmania/stepmania/wiki/Installing-on-macOS

>Also soon a warning has to be added that the current 32bit version of Stepmania will not work on macOS 2019 (10.15) - Mojave is the last macOS to support 32bit applications

As of (or because of) #1790, it is now possible to build SM5 for macOS as a 64bit application.

I think this issue can be closed.

---

Also, thank you for your feedback on the unrelated work I did as part of my master's thesis.  I genuinely appreciate it! 🙂
