### ISSUE TITLE
Make Noteskin default lambda globally

### ISSUE THREAD

**Issue by linuxtsunami** [stepmania/stepmania#1913]
Hi!

How can stepmania select "Lambda" or "Midi note" as default noteskin by default? 

Is there a way to set it up in Save/Preferences.ini ?

Thanks!

**Comment by RhythmLunatic** [comment]
Why "by default"? If you set it as the default noteskin then it is default for the whole game mode, until you select a different one per profile.

**Comment by linuxtsunami** [comment]
Doesn't seem to be what I see, everytime I restart stepmania, it's back to the default one. (red/fireworks arrows)

Do you mean that I need to create a profile for this do be remembered?

**Comment by RhythmLunatic** [comment]
No, if you set it as default in the settings then it should be global. No profile needed. 

Maybe it isn't working because of a bug, but if you want to do it manually you add the name of the noteskin to DefaultModifiers in Preferences.ini.

For example, "DefaultModifiers=Overhead, rio" where "rio" is the name of the noteskin

**Comment by linuxtsunami** [comment]
Where in the settings?

**Comment by RhythmLunatic** [comment]
Appearance options, I think

**Comment by linuxtsunami** [comment]
Yeah, I looked there but all I see is default and home, I don't see options for noteskins, and pressing enter on the theme itself doesn't open a submenu where I can choose a noteskin

**Comment by linuxtsunami** [comment]
As it stands, anything I put after 

DefaultModifiers=FailOff, Overhead

ex:
DefaultModifiers=FailOff, Overhead, lambda

just gets removed when I run stepmania again...

it goes back to 

DefaultModifiers=FailOff, Overhead

**Comment by quietly-turning** [comment]
You might have success by creating a `Static.ini` file and setting your DefaultModifiers there.

It sounds like you're using SM5.2, and you have not specified your OS, but I'll assume you're using Windows.  I think you'd want to:

1. navigate to `%APPDATA%\StepMania 5\Data\`
2. create a new text file and name it `Static.ini`
3. edit the file using notepad so that it contains

```ini
[Game-dance]
DefaultModifiers=FailOff, Overhead, lamda
```

I don't use Windows, SM5.2 has been effectively abandoned, and I've never actually tried creating a Static.ini file, but this should Work In Theory™.

**Comment by linuxtsunami** [comment]
I'm using Ubuntu :)

**Comment by quietly-turning** [comment]
The location might be `~/.stepmania-5.0/Data/Static.ini` then.

**Comment by linuxtsunami** [comment]
I actually created a profile on a hunch that it might remember the noteskins, and it did!

So all is good, thank you very much for your reply guys
