### ISSUE TITLE
Crashes on boot in windowed or fullscreen mode with RX480

### ISSUE THREAD

**Issue by Lythimus** [stepmania/stepmania#2052]
I've run StepMania for years, but for some reason it's crashing now when I'm trying to boot. It definitely seems to be stemming from OpenGL not playing nicely with my Radeon RX480, which StepMania has been running on for years. I uninstalled and reinstalled all the drivers. Also, other games / benchmarks seem to work fine.

3.9a rc2, 4.0 CVS build 1112, and 5 all seem to crash when trying to load RageDisplay_OGL::RageDisplay_OGL(). I've attached a log file from 4.0 CVS since 5 isn't generating a log file as far as I can tell.
[crashinfo.txt](https://github.com/stepmania/stepmania/files/5179054/crashinfo.txt)

Edit: My OpenGL info is:
Renderer: Radeon (TM) RX 480 Graphics
Vendor: ATI Technologies Inc.
Version: 4.6.13596 Core Profile Forward-Compatible Context 20.5.1 27.20.1017.1011
Shading language version: 4.60

Graphics drivers:
Radeon Graphics Drivers Adrenalin 2020 20.5.1 5-25-2020

**Comment by geefr** [comment]
Okay so getting a crash dump from sm5 (preferably from the 5_1-new branch) would be handy, but if it's crashing in all sounds like a system issue.

Crash dump definitely says it's crashing inside the graphics driver, this tends to only happen when an application does something well out of spec. Stepmania is a bit weird but I don't think it breaks too many rules. Odd that you've got gl 4.6 support but it still crashes..

From the log it says you're running Windows 8? That could be related (say, amd's drivers may not support that properly, 8 was weird).
Otherwise the main question would be whether other opengl games/benchmarks work correctly. If it's just stepmania suggests a bug here, otherwise something in your system. (Try this, looks like a half decent stress tester: https://www.geeks3d.com/gputest/)

**Comment by coderjo** [comment]
> From the log it says you're running Windows 8? That could be related (say, amd's drivers may not support that properly, 8 was weird).

Microsoft, in their divine wisdom, broke the APIs to query the version of Windows a program is running on. From MSDN:

> With the release of Windows 8.1, the behavior of the GetVersion API has changed in the value it will return for the operating system version. The value returned by the GetVersion function now depends on how the application is manifested.

> Applications not manifested for Windows 8.1 or Windows 10 will return the Windows 8 OS version value (6.2). Once an application is manifested for a given operating system version, GetVersion will always return the version that the application is manifested for in future releases. To manifest your applications for Windows 8.1 or Windows 10, refer to Targeting your application for Windows.

The helper functions IsWindows8* and IsWindows10* are documented the same way.

**Comment by geefr** [comment]
Oh...fun, thanks microsoft.. (Thanks for the info)

**Comment by Lythimus** [comment]
I was running Window 10 Pro Version 1511 (OS Build 10586.1176), but updated to 1903 (OS Build 18362.30), and that seems to have solved the problem. I have no idea what changed, but am happy it's working again. Some libraries may have gotten messed up, but I know the disk is working well because I ran spinrite level 4 on it not long ago.

For more background, I had already run FurMark, but ran it again for 30 minutes at max resolution with no hiccups. I also ran TessMark X64 OpenGl 4.0 with no hiccups. I ran the OpenGL Extensions Viewer Rendering tests 3.0 - 4.5 testing all the pipelines at max settings.
