### ISSUE TITLE
Single Player (P1) -> Versus -> Loads Same Profile

### ISSUE THREAD

**Issue by SpoOkyMagician** [stepmania/stepmania#226]
Not exactly sure if this is bad or not but, if you start single player and pick versus, it loads (first?) profile which is my main. So, it loads/uses the same profile for both players. This was done with the nightly build: Stepmania 5 825 2014-07-11_11-16-38

https://dl.dropboxusercontent.com/u/105712481/same_profile.png

edit: Dunno why 2 Player options are enabled for single player... :\

edit: Picking couple crashes the game. Kinda expected that though...

edit: Seems it loads the same profile. Not first one. (Just FYI.)

edit: Why is double enabled for 2 players? This is single player... Not two...

**Comment by SpoOkyMagician** [comment]
Seems to be fixed in 5.0.7 I will close this.

**Comment by lomdr** [comment]
It's a carry over from DDR 1st Mix - SuperNOVA2 arcade:  You need 2 Credits in order to play Doubles, which is the same amount needed to play Versus.  There is a Joint Premium option in the operator's menu for the arcade versions, but that also enables verses for 1 credit, so not many places use Joint Premium.  It's been a feature way back in the 3.0 prerelease days
