### ISSUE TITLE
Delete songs from UI

### ISSUE THREAD

**Issue by Noyabronok** [stepmania/stepmania#417]
It is inconvenient having to find the song in the file system to delete.  I'd like to request an option to delete songs from the UI, maybe with some key combination like Ctrl+Del.  It would save me a lot of time when organizing new songs.

**Comment by Wallacoloo** [comment]
I vote against moving songs into a stepmania-specific trash bin, as then it becomes an issue of users asking "where did my disk space go?" when they think their songs have actually been deleted.

In my XFCE version, at least, the Trash folder is in `~/.local/share/Trash`. Within it, there is a `files` folder that contains the actual trashed files, along with an `info` folder that contains entries for each deleted file, specifying where it came from and when it was deleted. The format is pretty straight-forward.

Gnome [appears to use the same scheme](http://karuppuswamy.com/wordpress/2010/06/08/how-to-manage-trash-from-command-line-in-gnome-delete-list-restore-and-empty/), including the metadata format, since at least 2010. KDE does too. I think we could go ahead and assume that Linux DEs trash files in `~/.local/share/Trash` (or rather, `$XDG_DATA_HOME/Trash` if that env variable is set) and if that directory doesn't exist, create it and issue a warning.

[This](http://stackoverflow.com/a/17974223/216292) S.O. post includes some code for trashing files on both Linux and Windows - might be a useful reference.

I'm going to go ahead and try to tackle this issue, though it may take some time as I'm totally unfamiliar with the Stepmania codebase.

**Comment by kyzentun** [comment]
I'm slightly leery of having it as a globally available lua function because it would make it easier for bad themes (or even simfiles) to screw up people's song folders.  (though that is already possible by other means, this would just make it easier)
Even with the desktop environment trash problem solved, the user interface side is hard to come up with a good secure solution for.

**Comment by shakesoda** [comment]
implemented by #526
