### ISSUE TITLE
beat songs do not play a preview during song selection

### ISSUE THREAD

**Issue by ZeroTheSavior** [stepmania/stepmania#488]
I have about 200+ songs, and preview music doesn't play for any of them.

SM beta 4a in portable mode, Windows 7 x64 & Windows 8 x64.

**Comment by Jousway** [comment]
yeah GL with making this work

because so many darn keysounds herpderp, this is going to be hard for older pc's to load all that stuff

if you havent noticed when you start a beat song on sm5, it takes longer to load than a normal song because of the keysounds, like a ton of games try to avoid this, games like for example krazy rain use preview songs that are just basicly cut MP3's with the keysounds already in them

imagine telling SM to render 200+ beat songs, oh hell no

what ya could do is generate a lets say sample.mp3 for all those songs and then using some lua magic play that when you hover over them hehu

**Comment by kyzentun** [comment]
Jousway does not speak for any developer.

If all bms songs have a preview.ogg, it should be possible to add a feature for playing them as the preview music.

**Comment by Jousway** [comment]
and kyzentun is a fucking retard so ignore him

**Comment by ZeroTheSavior** [comment]
Well, that's great. Every single one of them has a preview.ogg.

**Comment by kyzentun** [comment]
PS:  It'd take me a few minutes to implement this in my custom theme where I already have a custom music wheel for other reasons, but for common use in other themes it'll take somewhat longer.  And my custom theme requires 5.0.6.

**Comment by kyzentun** [comment]
Done.  https://github.com/stepmania/stepmania/commit/9381276fd3313d8ebde4718c4c05907ba69062da

**Comment by kyzentun** [comment]
@ZeroTheSavior Do those BMS files have a tag that says what file to use for the preview?  Or does it have to be "preview.ogg"?

**Comment by ZeroTheSavior** [comment]
They do have a preview tag, but it seems to specify the wrong file... All of mine say preview.wav, but they all contain preview.ogg.

Oh well, it's the fault of whoever made the beatmaps.

**Comment by kyzentun** [comment]
So, I'm going to add the preview tag to NotesLoaderBMS, and use whatever the preview tag says.  If the preview tag points to the wrong thing, then the bms has to be fixed.
