### ISSUE TITLE
Can't grab children from screen's decorations

### ISSUE THREAD

**Issue by YungDaVinci** [stepmania/stepmania#490]
Not sure if this is intentional, but you can't grab a screen's children from it's decorations file.
Nothing is returned. (literally nothing, not even nil)

**Comment by kyzentun** [comment]
I need to see actual code for the whole theme to see what is going wrong here.

**Comment by YungDaVinci** [comment]
(msg is a function that return SCREENMAN:SystemMessage(message))

local children
local t = Def.ActorFrame{
	OnCommand=function(self)
	children = SCREENMAN:GetTopScreen():GetChildren()
	if children then msg("Yay") else msg("Boo")  end
	end
}

return t

**Comment by dguzek** [comment]
It seems to be more an issue that OnCommand functions aren't triggered.  With the following code:

```
Trace("We are in the SWME decorations file.")

return Def.ActorFrame {
	OnCommand=function(self)
		Trace("We are in the SWME decorations OnCommand!")
	end
}
```

The first trace is logged but the second (inside the OnCommand) isn't.

**Comment by kyzentun** [comment]
Now I remember exactly why this happens:  The ActorFrame that you return loses custody of all its children and is thrown out.  The main layer of the screen takes all the children in.
https://github.com/stepmania/stepmania/blob/master/src/ScreenWithMenuElements.cpp#L80-L94

So, stick your stuff in a child of the decorations layer.

**Comment by kyzentun** [comment]
Decorations is a proper child now.
https://github.com/stepmania/stepmania/commit/0318f07d2ddcc330e424e56e4e357cfaf27630bc

**Comment by sigatrev** [comment]
Making Decorations a child breaks compatibility.

**Comment by kyzentun** [comment]
Changed it back:  https://github.com/stepmania/stepmania/commit/05fb09323e6dc324976bb565fc8afd6a8be6ca63
freem found the reason by digging through sourceforge commit history:  http://sourceforge.net/p/stepmania/mailman/message/18960756/ "experimental: load 'decorations' BGAnimation and make decorations children of the Screen so that their draworder relative to other children of the Screen can be controlled"

So, for themers, this means that anything special the decorations layer needs to do must be done by a child of the frame that is returned.
