### ISSUE TITLE
EditMode: Scrolling factor values

### ISSUE THREAD

**Issue by phurccon** [stepmania/stepmania#527]
I don't know if this is a new feature or a bug but every time i add a new scrolling factor value, the other scroll factor value below it will disappear automatically so i will have to redone all the scrolling factors afterwards when i only want to change the beat position of one of them

**Comment by kyzentun** [comment]
Are you on 5.0.5?  5.0.5 had a bug that could cause something like this.  It should be fixed in 5.0.6.

**Comment by phurccon** [comment]
no i'm on 5.0.6
some people found this change helpful though, so i guess it should be a preference?

**Comment by kyzentun** [comment]
It's actually a result of a crash fix.
Stepmania doesn't allow two consecutive identical timing segments, because they're redundant.
When you add or change a timing segment, if the new value is the same as the timing segment before it, it removes the segment.  If the new value is the same as the timing segment after it, the next timing segment is removed.
For example, let's say you set the scroll factor at beat 0 to 1.2.  Then you set the scroll factor at beat 4 to 1.5.  If you set the scroll factor at beat 2 to 1.5, the segment at beat 4 becomes redundant, so it's removed.

When edit mode didn't check for redundant timing segments, it was possible to crash stepmania by inserting redundant timing segments in edit mode, and then trying to play.

Edit mode has menu choices for shifting all timing segments up or down, maybe that needs to be extended to allow only shifting timing segments of a particular type.

**Comment by phurccon** [comment]
Particular timing shift would be great, since i (really) used to work on scrolling factors by "using" redundant timing segments.
Now that you mention it, I remember wanting something like copying particular timing values...

**Comment by kyzentun** [comment]
Added shifting and copy pasting region timing data in #543.
