### ISSUE TITLE
Cannot copy/paste timing data in Edit Mode

### ISSUE THREAD

**Issue by DXUltimate** [stepmania/stepmania#532]
Title pretty much says it all. When I'm trying to create a simfile with StepMania 5.0.7rc (or 5.0.6, 5.0.5, etc), we cannot copy and then paste added timing data. I have only done this with BPMs and it is tedious adding them in manually especially if it's the same "gimmicks" for 4 sets of 4measures each.

Steps to dupe:
1. Choose song to edit, or create
2. Place timing data (BPMs) on measures
3. Select area using the space bar then hit F4 > Copy Timing Data
4. Then press F4 > Paste timing data in a different area.

**Comment by kyzentun** [comment]
Looking at the code, this is a case of a serious misnomer.  What those menu choices actually do is copy all the timing data for the current Steps (the chart being edited) to a clipboard, so that it can then be pasted onto a different Steps, to make both Steps have the same timing data.

Separate menu choices need to be added that copy the timing data in the selected region somehow so that it can be pasted at a different beat.

**Comment by kyzentun** [comment]
Added shifting and copy pasting region timing data in #543.
