### ISSUE TITLE
CMake build fails for CMake versions < 3.0

### ISSUE THREAD

**Issue by Wallacoloo** [stepmania/stepmania#549]
A recent [commit](https://github.com/stepmania/stepmania/commit/c49d78f5fc82bcf21d2fe456db2ab2b89539dad2#diff-af3b638bc2a3e6c650974192a53c7291R304) altering the CMake build system uses the string CONCAT command. This command appears to only be available for CMake >= 3.0 (Compare the [3.0](http://www.cmake.org/cmake/help/v3.0/command/string.html) docs to the [2.8](http://www.cmake.org/cmake/help/v2.8.8/cmake.html#command:string) docs) and prevents compilation on anything less than that. The CMake version available through standard Ubuntu repositories is still only at 2.8.12.2, so I don't think it's reasonable to rely upon CMake 3.0 as of yet (but feel free to challenge that if you disagree).

Complete CMake log:
```
$ cmake --version
cmake version 2.8.12.2
$ cmake ..
-- The C compiler identification is GNU 4.9.1
-- The CXX compiler identification is GNU 4.9.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- checking for module 'freetype2'
--   found freetype2, version 17.1.11
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "17.1.11") 
-- Found GTK2_GTK: /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so  
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found PCRE: /usr/include  
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit in /usr/lib/x86_64-linux-gnu/libbz2.so
-- Looking for BZ2_bzCompressInit in /usr/lib/x86_64-linux-gnu/libbz2.so - found
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found XRANDR: /usr/lib/x86_64-linux-gnu/libXrandr.so  
-- Found OGG: /usr/lib/x86_64-linux-gnu/libogg.so  
-- Found VORBIS: /usr/lib/x86_64-linux-gnu/libvorbis.so  
-- Found VORBISFILE: /usr/lib/x86_64-linux-gnu/libvorbisfile.so  
-- Found LIBMAD: /usr/lib/x86_64-linux-gnu/libmad.so  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- checking for module 'libpulse'
--   found libpulse, version 4.0
-- Found PULSEAUDIO: /usr/include  
-- Found ALSA: /usr/lib/x86_64-linux-gnu/libasound.so (found version "1.0.28") 
-- checking for module 'jack'
--   found jack, version 1.9.10
-- Could NOT find JACK (missing:  JACK_INCLUDE_DIRS JACK_LIBRARIES) 
-- Found OSS: /usr/include  
-- -- At least one sound library was found. Do not worry if any were not found at this stage.
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found yasm: /usr/bin/yasm  
CMake Error at CMakeLists.txt:304 (string):
  string does not recognize sub-command CONCAT


-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found GLEW: /usr/include  
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Configuring incomplete, errors occurred!
See also "/home/colin/proj/stepmania/build-release/CMakeFiles/CMakeOutput.log".
See also "/home/colin/proj/stepmania/build-release/CMakeFiles/CMakeError.log".
```
Attempting to run make afterwards results in
```
$ make
make: *** No targets specified and no makefile found.  Stop.
```
Which make sense because no makefile was generated.

**Comment by roothorick** [comment]
Of all Debian and Ubuntu releases, NONE are providing 3.0.x yet. Each and every one is on 2.8.x. Jessie (Debian 8) will... that's it. How did this not get caught?

**Comment by wolfman2000** [comment]
I can tell you how this did not get caught.

1. I had cmake 3.0.2 downloaded and installed manually.
2. I mixed up the doc version pages when writing c49d78f and forgot about it.

Now, this does bring up some fair points. On the one hand, as both @Wallacoloo and another Omnipotent brought up, not all of the linux OSes provide cmake 3.0 or higher yet. On the other hand, the cmake IRC channel encourages users to upgrade. I was debating whether to upgrade to cmake 3.0 or higher due to other commands I wanted to utilize.

As far as how to resolve this one? That's tricky. When I tried using the normal set command with two variables being interpolated, I was getting some warnings about how the variables were not separated by whitespace or something. I prefer to not work with warnings whenever possible. Hence the finding of concat.

I can see about looking into a poor man's replacement for now, but I would also hope that, if you do not care to compile cmake manually, that the Linux distros start offering cmake 3.0 or higher soon.

**Comment by dguzek** [comment]
Just to chime in on the OS X side of things, the last time we spoke about this I realized I was running CMake 2.9.x because it was what Homebrew installed when I typed `brew install cmake`

The very next day CMake was upgraded to 3.2.1 when I updated Homebrew as usual.  So, from the perspective of OS X devs, there's not very many good reasons to continue supporting old CMake.

**Comment by kyzentun** [comment]
Debian is what I do all my work on, and probably most Linux users are on that or Ubuntu.  Since none of them provide a package for new CMake, you're asking every Linux user to go download cmake and install it by hand. (which means "./bootstrap && make && make install", so almost identical to installing an autoconfiscated package)
I've installed packages that way dozens of times over the years, but it's a pain to have to go back to it when every other dependency can be installed with a normal package manager.
So I say fix it to work with CMake 2.8.

**Comment by Wallacoloo** [comment]
Is `String(CONCAT ...)` a module, or a compiled builtin? Because if it's a module it may be possible to target Cmake 2.8 but distribute the .cmake file that provides the `CONCAT` function along with the Stepmania sources (dependent upon licensing and such).

**Comment by Wallacoloo** [comment]
Otherwise, I agree with kyzentun. I would certainly not go to the trouble to compile cmake from source if I was new to Stepmania. And adding new software sources (if one exists for their OS) to get an up-to-date CMake is something many intro-level Linux aren't actually very familiar with. Note however that Linux users may still be able to use the current autotools-based build system, if the plan is to keep that around. But having separate build systems for Linux vs other OS's sounds like the wrong path to take.

**Comment by wolfman2000** [comment]
@Wallacoloo string(CONCAT) is a built-in function. The goal is to replace autotools (and Visual Studio projects and Xcode projects) with cmake for all OSes so that users can decide how they want to build.

**Comment by shakesoda** [comment]
Do anything you can to keep it at 2.8 until there's an ubuntu LTS on > 2.8, IMO.

**Comment by wolfman2000** [comment]
@Wallacoloo Give the latest master a shot. Commit f78574e should handle it.

**Comment by Wallacoloo** [comment]
:thumbsup: Works great for me.

**Comment by wolfman2000** [comment]
Mission completed.
