### ISSUE TITLE
Make using Enter to give up optional.

### ISSUE THREAD

**Issue by JeroenMathon** [stepmania/stepmania#589]
I and many people have different play styles and key mappings.
Mine has my right hand very close to enter.
So i sometimes accidently tap it which coauses the game to give up on the song.
i already looked at the source code since changing the key bindings in the options menu did not seem to work.

But could not get it to work my self.

Please add this feature becaouse i love the game but can't stand the giving up on accident.

**Comment by shakesoda** [comment]
This is why delayed back is an option, start doesn't just immediately give
up unless you set it to do so.


- Colby

**Comment by kyzentun** [comment]
In the default theme, you must hold the start (enter) button for 2.5 seconds for it to give up, and not press any other buttons for it to give up.
If it's giving up instantly instead of having a delay, that's poor behavior on the part of the theme, because the delay is there to prevent this problem.

You could try mapping your keys to Player 2, and mapping something else as the start button.  If only Player 2 is active, the Player 1 start button is ignored during gameplay.

**Comment by JeroenMathon** [comment]
I am using this theme http://cyberiastyle.skr.jp/

**Comment by dguzek** [comment]
CyberiaStyle has ```GiveUpSeconds``` set to *nothing* under [ScreenGameplay]

Change the Metrics.ini file, find ```GiveUpSeconds=``` and change it to something like ```GiveUpSeconds=0.333```

**Comment by JeroenMathon** [comment]
Thanks!
