### ISSUE TITLE
Which SDK is required to build on Windows 8.1?

### ISSUE THREAD

**Issue by AngledLuffa** [stepmania/stepmania#700]
I'm trying to build StepMania from source on Windows 8.1 so I can start contributing fixes to some of the issues I've reported.  I installed the Windows SDK, which says it includes directx:

https://msdn.microsoft.com/en-gb/windows/desktop/bg162891

However, the download linked does not have `DxErr.h`, whch throws off `FindDirectX.cmake`  It also doesn't have `d3dx9.lib` , although it has `d3d9.lib` as well as `d3d10.lib` and `d3d11.lib` .  Is this the right package to download and use on Windows 8.1?  If so, which file would be a substitute for `DxErr.h` , and if not, what should I download instead?

Thanks!

**Comment by AngledLuffa** [comment]
This page suggests either replacing include files for use with the Windows SDK or installing the 2010 version of the DirectX SDK:

https://msdn.microsoft.com/library/windows/desktop/ee663275.aspx

**Comment by basisbit** [comment]
I am also wondering, what is the DirectX SDK even required for? SDL provides DirectX / OpenGL context, so I don't really see the need. Thanks in advance.
Also, compiling on Windows 10 also fails because of 
> CMake Error at CMake/Modules/FindDirectX.cmake:14 (message): "Could not find Microsoft DirectX SDK installation!"

Installation of that package is not possible on windows 10. Any header files / ... of DirectX are part of the Windows Development SDK nowadays.

**Comment by Prcuvu** [comment]
> Installation of that package is not possible on windows 10.

Why isn't it possible? I have installed DirectX SDK (June 2010) on my Windows 10 PC.
