### ISSUE TITLE
Fatal error on Virtual Machine run on VMWare Fusion in Mac OSX

### ISSUE THREAD

**Issue by hudsonab** [stepmania/stepmania#743]
Getting this error with 3d acceleration enabled:

There was an error while initializing your video card.

Please do not file this error as a bug!  Use the web page below to troubleshoot this problem.

http://old.stepmania.com/stepmaniawiki.php?title=Video_Driver_Troubleshooting

Video Driver: Standard VGA Graphics Adapter

Initializing opengl...
SetVideoMode failed: The WGL_EXT_swap_control extension is not supported on your computer.;The WGL_EXT_swap_control extension is not supported on your computer.;The WGL_EXT_swap_control extension is not supported on your computer.;The WGL_EXT_swap_control extension is not supported on your computer.

Initializing d3d...
Your system is reporting that Direct3D hardware acceleration is not available.  Please obtain an updated driver from your video card manufacturer.

**Comment by jansol** [comment]
RTFM: "Please do not file this error as a bug! Use the web page below to troubleshoot this problem."

**Comment by RafalLauterbach** [comment]
"Use the web page below to troubleshoot this problem." is no longer valid solution.

I also have actual drivers with 3d acceleration on (using VirtualBox). (relating to other simmilar topic)

I actually try to run this program on my virtual machine only because casual user (my friend) completely failed in installing it, so I have to virtualize his system and try to somehow make it work. I must say installation is super user unfriendly.
