### ISSUE TITLE
Megalovania (taronuke)

### ISSUE THREAD

**Issue by Defluxit** [stepmania/stepmania#981]
Everytime I load up the file it crashes for no reason. It worked before I don't know why it doesn't work anymore. I'm on StepMania 5. I'm using the 5.0.9 client.

**Comment by kyzentun** [comment]
Post the crash log.

**Comment by YungDaVinci** [comment]
Not sure what the issue is, but it works fine on 5.0.10 for me. I'd recommend upgrading.

**Comment by Defluxit** [comment]
[crash log.txt](https://github.com/stepmania/stepmania/files/85213/crash.log.txt)

**Comment by Defluxit** [comment]
I've downloaded StepMania 5.0.10 and I'm going to see if it works correctly or not.

**Comment by Defluxit** [comment]
I simply had to update to the latest client, I'm sorry for bothering you guys.

**Comment by kyzentun** [comment]
Weirdly, it worked for me in 5.0.9 and ultralight.  Maybe it was something weird in your config.

**Comment by Defluxit** [comment]
Well, it worked once or twice, but once again it has crashed including on 5.0.10. I will give you the crash log once I get home.

**Comment by kyzentun** [comment]
Someone on IRC guessed that you might have Stepmania installed in Program Files.  Is that the case?

**Comment by Defluxit** [comment]
Yeah I installed it under Program Files (x86) for ease of access.

**Comment by kyzentun** [comment]
Well, that causes problems because UAC on Windows prevents stepmania from writing to simfile folders and stuff.  This comes up whenever someone tries to edit a simfile and can't find where their hours of work went.

In this specific case, that simfile writes a special save file to the song folder to track how many times it has been played.  Since UAC gets in the way, the file can't be opened, and the attempt to read/write to it causes a crash.

Install Stepmania to your desktop or C:/Games or something, or stick your custom songs in %APPDATA%/StepMania 5.0/Songs/ (and custom themes in %APPDATA%/StepMania 5.0/Themes/ and so on for NoteSkins).

**Comment by Defluxit** [comment]
To make it easier could I just drag the entire StepMania 5 folder into C:/Games?

**Comment by kyzentun** [comment]
Yes.

**Comment by Defluxit** [comment]
Alright, thank you for helping me out with this problem. I appreciate your time!
