### ISSUE TITLE
Hang going into Graphics/Sound Options Menu

### ISSUE THREAD

**Issue by KillerClaw** [stepmania/stepmania#986]
Game hangs when attempting to enter "graphics/sound options" menu. See both "Not Present" texts but screen stays black, causes system to slow down, and must be killed from task manager.

OS: Win 10 - 64 bit

Logs:
[log.txt](https://github.com/stepmania/stepmania/files/89835/log.txt)
[userlog.txt](https://github.com/stepmania/stepmania/files/89837/userlog.txt)

**Comment by NoUserNameRequired** [comment]
Open %APPDATA%/StepMania 5/Preferences.ini and go to VideoRenderers=.
Change it from opengl,d3d to d3d,opengl. I had the same problem and that is what fixed it for me.
I wonder why the Direct3D renderer isn't chosen automatically because I had really big performance issues on the opengl renderer and using the 3d3 one fixed all of them.

**Comment by kyzentun** [comment]
The d3d renderer doesn't work with some blend modes and has some visual bugs.

**Comment by kyzentun** [comment]
Fixed in current master.  It's from testing lots of video modes just to get a list of choices.
https://github.com/stepmania/stepmania/commit/79f403708820a288efdf31ebc24843c32d090357
